"""Common interface for evaluating fields on robot body surfaces."""

from .core import (
    Backend,
    BackendRegistry,
    BodyField,
    DeviceKind,
    LinkSurface,
    LinkState,
    LinkStateProvider,
    Matrix3,
    ParallelAxis,
    ParallelProfile,
    PreparedBackend,
    QuantitySpec,
    QuantityValue,
    RobotState,
    RobotSurfaceModel,
    SurfaceFieldQuery,
    SurfaceMesh,
    SurfacePoint,
    Vector3,
    default_backend_registry,
)
from .obstacles import AxisAlignedBoxObstacle, DistanceObstacle, SphereObstacle

__all__ = [
    "AxisAlignedBoxObstacle",
    "Backend",
    "BackendRegistry",
    "BodyField",
    "DeviceKind",
    "DistanceObstacle",
    "LinkSurface",
    "LinkState",
    "LinkStateProvider",
    "Matrix3",
    "ParallelAxis",
    "ParallelProfile",
    "PreparedBackend",
    "QuantitySpec",
    "QuantityValue",
    "RobotState",
    "RobotSurfaceModel",
    "SurfaceFieldQuery",
    "SurfaceMesh",
    "SurfacePoint",
    "SphereObstacle",
    "Vector3",
    "default_backend_registry",
]
